server:
  port: 8084

spring:
  application:
    name: kredinbizde-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/orders/**
